# Use an official Python runtime as a parent image
FROM python:latest

# Install any dependencies system for the app
RUN apt-get update && apt-get install -y \
    python3-pip nmap\
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Make port 80 available to the world outside this container
EXPOSE 80

# Command to run the application
CMD ["python", "main.py"]