version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    env_file:
      - ./dev/.env.dev  # Pour l'environnement de développement
      # - ./prod/.env.prod  # Pour l'environnement de production
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_PASSWORD}
      MYSQL_DATABASE: ${MARIADB_DATABASE}
    volumes:
      - ./dev/server_mariadb_dev/data:/var/lib/mysql
      - ./dev/server_mariadb_dev/conf:/etc/mysql/conf.d
      - ./dev/server_mariadb_dev/logs:/var/log/mysql

  mongodb:
    image: mongo:latest
    env_file:
      - ./dev/.env.dev
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    volumes:
      - ./dev/server_mongodb_dev/data:/data/db
      - ./dev/server_mongodb_dev/logs:/var/log/mongodb

  lan-audacity-app:
    build: ./dev/lan-audacity_app_dev
    env_file:
      - ./dev/.env.dev
    environment:
      APP_PORT: ${APP_PORT}
      LOG_LEVEL: ${LOG_LEVEL}
    ports:
      - "${APP_PORT}:5317"
    volumes:
      - ./dev/lan-audacity_app_dev/src:/app/src
      - ./dev/lan-audacity_app_dev/data:/app/data
      - ./dev/lan-audacity_app_dev/logs:/app/logs
