version: 1

formatters:
  simple:
    format: '%(levelname)s - %(message)s'
  custom:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: WARNING
    formatter: simple
    stream: ext://sys.stdout
  file_handler:
    class: logging.FileHandler
    level: DEBUG
    formatter: custom
    filename: logs/app.log
    encoding: utf-8

loggers:
  root:
    level: DEBUG
    handlers: [console, file_handler]
    propagate: no